name: list_shopping_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Group 79.png
 
  # fonts:
  #   - family: GT-Eesti-Display
  #     fonts:
  #       - asset: fonts/GT-Eesti-Display-Regular
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

